package com.codechix.explorers.solardata.geopolitical;

import com.google.common.collect.ImmutableList;

public abstract class CaliforniaCounties {

    public static final ImmutableList<String> ALL_COUNTIES = new ImmutableList.Builder<String>()
            .add("Alameda")
            .add("Alpine")
            .add("Amador")
            .add("Butte")
            .add("Calaveras")
            .add("Colusa")
            .add("Contra Costa")
            .add("Del Norte")
            .add("El Dorado")
            .add("Fresno")
            .add("Glenn")
            .add("Humboldt")
            .add("Imperial")
            .add("Inyo")
            .add("Kern")
            .add("Kings")
            .add("Lake")
            .add("Lassen")
            .add("Los Angeles")
            .add("Madera")
            .add("Marin")
            .add("Mariposa")
            .add("Mendocino")
            .add("Merced")
            .add("Modoc")
            .add("Mono")
            .add("Monterey")
            .add("Napa")
            .add("Nevada")
            .add("Orange")
            .add("Placer")
            .add("Plumas")
            .add("Riverside")
            .add("Sacramento")
            .add("San Benito")
            .add("San Bernardino")
            .add("San Diego")
            .add("San Francisco")
            .add("San Joaquin")
            .add("San Luis Obispo")
            .add("San Mateo")
            .add("Santa Barbara")
            .add("Santa Clara")
            .add("Santa Cruz")
            .add("Shasta")
            .add("Sierra")
            .add("Siskiyou")
            .add("Solano")
            .add("Sonoma")
            .add("Stanislaus")
            .add("Sutter")
            .add("Tehama")
            .add("Trinity")
            .add("Tulare")
            .add("Tuolumne")
            .add("Ventura")
            .add("Yolo")
            .add("Yuba")
            .build();

}
